server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:employeedb
#    url: jdbc:mysql://localhost:3306/employeedb?allowPublicKeyRetrieval=true&&useSSL=false&serverTimezone=UTC
#    username: root
#    password: admin
  h2:
    console:
      enabled: true
  liquibase:
    enabled: true
    change-log: classpath:sql/changelog.yml

api:
  version: @revision@

springdoc:
  packagesToScan: com.springboot.demo.employee
  pathsToMatch: /**
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    supportedSubmitMethods: ["get", "post", "put", "delete"]
