server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employeedb?allowPublicKeyRetrieval=true&&useSSL=false&serverTimezone=UTC
    username: root
    password: admin

api:
  version: @revision@

springdoc:
  packagesToScan: com.springboot.demo.employee
  pathsToMatch: /**
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    supportedSubmitMethods: ["get", "post", "put", "delete"]
