server:
  port: 8080

spring:
  datasource:
#    url: jdbc:h2:mem:employeedb
    url: jdbc:oracle:thin:@localhost:1521:orcl #?allowPublicKeyRetrieval=true&&useSSL=false&serverTimezone=UTC
    username: dbuser
    password: dbpass
    proxy-user: root

#  h2:
#    console:
#      enabled: true
  liquibase:
    enabled: true
    change-log: classpath:sql/changelog.yml

api:
  version: @revision@

springdoc:
  packagesToScan: com.springboot.demo.employee
  pathsToMatch: /**
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    supportedSubmitMethods: ["get", "post", "put", "delete"]
