insert into employee(id, name, department, machine) values (1, 'James', 'Development', 'Windows');
insert into employee(id, name, department, machine) values (2, 'Michael', 'Production', 'MacOS');
insert into employee(id, name, department, machine) values (3, 'Steve', 'Testing', 'Linux');
insert into employee(id, name, department, machine) values (4, 'Emma', 'Customer Support', 'Windows');
insert into employee(id, name, department, machine) values (5, 'Sarah', 'Architecture', 'MacOS');
insert into employee(id, name, department, machine) values (6, 'Ethan', 'Operations', 'Linux');
insert into employee(id, name, department, machine) values (7, 'Ashley', 'Human Resources', 'Windows');
insert into employee(id, name, department, machine) values (8, 'Ryder', 'Management', 'MacOS');
insert into employee(id, name, department, machine) values (9, 'Olivia', 'Accounting & Finance', 'Windows');
insert into employee(id, name, department, machine) values (10, 'Madison', 'Design', 'MacOS');