-- BASIC SETUP STEPS

CONN SYS/admin AS SYSDBA;
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

CREATE USER ROOT IDENTIFIED BY secret;
GRANT CONNECT TO ROOT;
GRANT CREATE SESSION TO ROOT;
GRANT UNLIMITED TABLESPACE TO ROOT;
GRANT CREATE ROLE, ALTER ANY ROLE, DROP ANY ROLE TO ROOT;
GRANT CREATE TABLE, SELECT ANY TABLE, DELETE ANY TABLE, ALTER ANY TABLE TO ROOT;
GRANT CREATE ANY SEQUENCE, ALTER ANY SEQUENCE, DROP ANY SEQUENCE TO ROOT;
GRANT CREATE ANY TRIGGER, ALTER ANY TRIGGER, DROP ANY TRIGGER TO ROOT;

CREATE USER PROXY IDENTIFIED BY password;
GRANT CONNECT TO PROXY;
GRANT CREATE SESSION TO PROXY;
ALTER USER ROOT GRANT CONNECT THROUGH PROXY;

CONN ROOT/secret
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
CREATE ROLE RW_ROLE;
GRANT RW_ROLE TO PROXY;

--TO CLEANUP EVERYTHING

CONN ROOT/secret
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
DROP ROLE RW_ROLE;

CONN SYS/admin AS SYSDBA;
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

REVOKE ALL PRIVILEGES FROM PROXY;
REVOKE ALL PRIVILEGES FROM ROOT;
DROP USER PROXY CASCADE;
DROP USER ROOT CASCADE;